---
language: ruby
bundler_args: --without=extras
script: bundle exec rspec spec
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - rbx-2
  - jruby-1.7
  - ruby-head
  - jruby-head
allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
