---
language: ruby
script: rake test:coverage:run
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
